### ISSUE TITLE
I can't find the "build CustomBloon" (yes, me again, I know)

### ISSUE THREAD

**Issue by buttonmash147** [DarkTerraYT/CustomBloon#1]
I made sure everything required that was mentioned was installed but you lost me at the "build" part...
Pls help
![Bloonl](https://github.com/DarkTerraYT/CustomBloon/assets/137331119/64725a9c-2580-4993-a25f-93d92f33499a)

(purple, white & lead properties, health, size (?) & children of a BFB)
just in case

**Comment by buttonmash147** [comment]
just to clarify, I have 0 coding experience.

**Comment by DarkTerraYT** [comment]
Do you have the code download and it open in visual studio?

**Comment by buttonmash147** [comment]
> Do you have the code download and it open in visual studio?

yes (I used the "create mod" tool in the btd6 mod helper menu.)

**Comment by buttonmash147** [comment]
except i have .net 7.0

**Comment by DarkTerraYT** [comment]
well do you have all of the code (sorry for late response I forgot about this)
